display_update: Fix DISPLAY and XAUTH not working properly
Add error message if the variables are wrong.

Remove updating display for vim because it never worked.

diff --git a/bin/display_update b/bin/display_update
--- a/bin/display_update
+++ b/bin/display_update
@@ -1,4 +1,5 @@
 #!/usr/bin/env bash
+# shellcheck disable=2162
 
 # Copied from https://gist.github.com/mikeboiko/b6e50210b4fb351b036f1103ea3c18a9#file-update_display-sh
 
@@ -12,28 +13,25 @@
 # The solution:
 # When attaching to tmux session, update $DISPLAY for each tmux pane in that session
 # This is performed by using tmux send-keys to the shell.
-# This script handles updating $DISPLAY within vim also
 
-NEW_DISPLAY="$DISPLAY"
-NEW_XAUTH="$(xauth list "$DISPLAY")"
+NEW_DISPLAY="$(tmux show-env | sed -n 's/^DISPLAY=//p')"
+NEW_XAUTH="$(xauth list "$DISPLAY" 2> /dev/null)"
+CMD_DISPLAY="export DISPLAY=$NEW_DISPLAY"
+CMD_XAUTH="xauth add $NEW_XAUTH"
 
-if [[ -n "$NEW_DISPLAY" || -n "$NEW_XAUTH" ]]; then
+if [[ "$NEW_DISPLAY" = "" || "$NEW_XAUTH" = "" ]]; then
+    >&2 echo "$0 error: NEW_DISPLAY=$NEW_DISPLAY or NEW_XAUTH=$NEW_XAUTH is empty."
     exit 1
 fi
 
-# NEW_DISPLAY=$(tmux show-env | sed -n 's/^DISPLAY=//p')
-
-# Update $DISPLAY in bash, zsh and vim/nvim
+# Update $DISPLAY in bash, zsh.
+tmux display-message -p "Update DISPLAY and xauth"
 tmux list-panes -s -F "#{session_name}:#{window_index}.#{pane_index} #{pane_current_command}" | \
     while read pane_process
 do
     IFS=' ' read -ra pane_process <<< "$pane_process"
     if [[ "${pane_process[1]}" == "zsh" || "${pane_process[1]}" == "bash" ]]; then
-        tmux send-keys -t ${pane_process[0]} "export DISPLAY=$NEW_DISPLAY" Enter
-        tmux send-keys -t ${pane_process[0]} "xauth add $NEW_XAUTH" Enter
-    elif [[ "${pane_process[1]}" == *"vi"* ]]; then
-        tmux send-keys -t ${pane_process[0]} Escape
-        tmux send-keys -t ${pane_process[0]} ":let \$DISPLAY = \"$NEW_DISPLAY\"" Enter
-        tmux send-keys -t ${pane_process[0]} ":silent! xrestore" Enter
+        tmux send-keys -t "${pane_process[0]}" "$CMD_DISPLAY" Enter
+        tmux send-keys -t "${pane_process[0]}" "$CMD_XAUTH" Enter
     fi
 done
